dataset:
    workspace: new-workspace-x0ijl
    project: animal-detection-dy7jy
    version: 2
    format: coco
    overwrite: false
    download_dir: /home/jay/projects/squirrel-defender/data/sources/roboflow/dataset6/downloads

hdf5:
    annotation_file: _annotations.coco.json
    possible_splits:
        - train
        - test
        - valid
    save_dir: /home/jay/projects/squirrel-defender/data/sources/roboflow/dataset6
