dataset:
    workspace: k-rieger-chohm
    project: hoernchen
    version: 14
    format: coco
    overwrite: false
    download_dir: /home/jay/projects/squirrel-defender/data/sources/roboflow/dataset3/downloads

hdf5:
    annotation_file: _annotations.coco.json
    possible_splits:
        - train
        - test
        - valid
    save_dir: /home/jay/projects/squirrel-defender/data/sources/roboflow/dataset3
