# this cofig file list of datasets to be downloaded from roboflow
# these datasets are relevant to the squirrel detection model
datasets:
  dataset1: # squirrels
    workspace: squirrel-iest3
    project: squirrel-xgfti
    version: 1
    total: 641
    format: coco

  dataset2: # squirrels
    workspace: rayhan-papar-nfm40
    project: squirreldataset-zh4hp
    version: 1
    total: 1810
    format: coco

  dataset3: # squirrels
    workspace: k-rieger-chohm
    project: hoernchen
    version: 14
    total: 4051
    format: coco

  dataset4: # squirrels
    workspace: the-university-of-michigan-openmi
    project: chonky-squirrels-from-uofm
    version: 4
    total: 468
    format: coco

  dataset5: # squirrles
    workspace: squirrels-lyyup
    project: robin_squirrels
    version: 3
    total: 3062
    format: coco

  dataset6: # squirrels, cats, dogs, monkeys, birds. 
    workspace: new-workspace-x0ijl
    project: animal-detection-dy7jy
    version: 2
    total: 5998
    format: coco

save_dir: /home/jay/projects/squirrel-defender/data/sources/roboflow/downloads




  

